import fs from 'node:fs';import assert from 'node:assert/strict';
import * as T from 'file:///F:/%EA%B0%9C%EC%9D%B8/%EA%B2%8C%EC%9E%84%EA%B0%9C%EB%B0%9C/My%20pick%20Hero/prototype/node_modules/three/build/three.module.js';
const base="F:/개인/게임개발/My pick Hero/prototype/asset/char3d/rabbit-healer";
function read(p){const buf=fs.readFileSync(p),len=buf.readUInt32LE(12),j=JSON.parse(buf.subarray(20,20+len)),bin=20+len+8;
const data=i=>{const a=j.accessors[i],v=j.bufferViews[a.bufferView],n={SCALAR:1,VEC3:3,VEC4:4,MAT4:16}[a.type];assert.equal(a.componentType,5126);const values=[];for(let k=0;k<a.count;k++)for(let c=0;c<n;c++)values.push(buf.readFloatLE(bin+(v.byteOffset||0)+(a.byteOffset||0)+k*(v.byteStride||n*4)+c*4));return values;};
const nodes=j.nodes.map(n=>{const o=new T.Object3D();o.name=(n.name||'').replaceAll(':','');if(n.matrix)new T.Matrix4().fromArray(n.matrix).decompose(o.position,o.quaternion,o.scale);else{if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale);}return o;});
j.nodes.forEach((n,i)=>(n.children||[]).forEach(c=>nodes[i].add(nodes[c])));const scene=new T.Group();j.scenes[j.scene||0].nodes.forEach(i=>scene.add(nodes[i]));scene.updateMatrixWorld(true);
const bind=new Map();j.skins[0].joints.forEach((idx,i)=>bind.set(nodes[idx].name,new T.Matrix4().fromArray(data(j.skins[0].inverseBindMatrices),i*16).invert()));
function clip(name){const a=j.animations.find(a=>a.name===name);assert(a,'missing '+name);return new T.AnimationClip(name,-1,a.channels.map(c=>{const s=a.samplers[c.sampler],prop={rotation:'quaternion',translation:'position',scale:'scale'}[c.target.path],type=c.target.path==='rotation'?T.QuaternionKeyframeTrack:T.VectorKeyframeTrack;assert.notEqual(s.interpolation,'CUBICSPLINE');return new type(nodes[c.target.node].name+'.'+prop,data(s.input),data(s.output),s.interpolation==='STEP'?T.InterpolateDiscrete:T.InterpolateLinear);}));}
return {j,buf,bin,scene,nodes,bind,clip,get:n=>nodes.find(x=>x.name===n)};}
const source=read('F:/개인/게임개발/My pick Hero/prototype/asset/char/기본형_동작53.glb'),target=read(base+'/rabbit-healer-animated.glb');
const rest=target.nodes.map(n=>({p:n.position.clone(),q:n.quaternion.clone(),s:n.scale.clone()}));
const restore=()=>{target.nodes.forEach((n,i)=>{n.position.copy(rest[i].p);n.quaternion.copy(rest[i].q);n.scale.copy(rest[i].s);});target.scene.updateMatrixWorld(true);};
const pos=(r,n)=>new T.Vector3().setFromMatrixPosition(r.bind.get(n));
const quat=m=>{const p=new T.Vector3(),q=new T.Quaternion(),s=new T.Vector3();m.decompose(p,q,s);return q;};
function basis(r,l,rr,hip,head){const y=pos(r,head).sub(pos(r,hip)).normalize(),x=pos(r,l).sub(pos(r,rr));x.addScaledVector(y,-x.dot(y)).normalize();return new T.Quaternion().setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,new T.Vector3().crossVectors(x,y).normalize()));}
const align=basis(target,'mixamorigLeftArm','mixamorigRightArm','mixamorigHips','mixamorigHead').multiply(basis(source,'mixamorigLeftArm','mixamorigRightArm','mixamorigHips','mixamorigHead').invert()),inv=align.clone().invert();
const mapping={mixamorigHips:'Hips',mixamorigSpine:'Spine',mixamorigSpine1:'Spine1',mixamorigSpine2:'Spine2',mixamorigNeck:'Neck',mixamorigHead:'Head',mixamorigLeftShoulder:'LeftShoulder',mixamorigLeftArm:'LeftArm',mixamorigLeftForeArm:'LeftForeArm',mixamorigLeftHand:'LeftHand',mixamorigRightShoulder:'RightShoulder',mixamorigRightArm:'RightArm',mixamorigRightForeArm:'RightForeArm',mixamorigRightHand:'RightHand',mixamorigLeftUpLeg:'LeftUpLeg',mixamorigLeftLeg:'LeftLeg',mixamorigLeftFoot:'LeftFoot',mixamorigLeftToeBase:'LeftToeBase',mixamorigRightUpLeg:'RightUpLeg',mixamorigRightLeg:'RightLeg',mixamorigRightFoot:'RightFoot',mixamorigRightToeBase:'RightToeBase'};
const childPairs={mixamorigLeftArm:['mixamorigLeftForeArm','LeftForeArm'],mixamorigLeftForeArm:['mixamorigLeftHand','LeftHand'],mixamorigRightArm:['mixamorigRightForeArm','RightForeArm'],mixamorigRightForeArm:['mixamorigRightHand','RightHand'],mixamorigLeftUpLeg:['mixamorigLeftLeg','LeftLeg'],mixamorigLeftLeg:['mixamorigLeftFoot','LeftFoot'],mixamorigLeftFoot:['mixamorigLeftToeBase','LeftToeBase'],mixamorigRightUpLeg:['mixamorigRightLeg','RightLeg'],mixamorigRightLeg:['mixamorigRightFoot','RightFoot'],mixamorigRightFoot:['mixamorigRightToeBase','RightToeBase']};
const ordered=[];target.scene.traverse(n=>{if(mapping[n.name])ordered.push(n);});assert.equal(ordered.length,22);
const corrected=new Map(ordered.map(n=>{let q=quat(target.bind.get(n.name));if(childPairs[n.name]){const [tc,sc]=childPairs[n.name],a=pos(target,tc).sub(pos(target,n.name)).normalize(),b=pos(source,'mixamorig'+sc).sub(pos(source,'mixamorig'+mapping[n.name])).normalize().applyQuaternion(align);q.premultiply(new T.Quaternion().setFromUnitVectors(a,b));}return[n.name,q];}));
const clips=[],report=[];
let idlePose;
for(const [name,srcName]of [['hit','전투_피격(머리)'],['death','전투_사망']]){
const src=source.clip(srcName),m=new T.AnimationMixer(source.scene);m.clipAction(src).setLoop(T.LoopOnce,1).play();const duration=src.duration,steps=Math.ceil(duration*30),times=[],values=new Map(ordered.map(n=>[n.name,[]])),rootValues=[];
for(let i=0;i<=steps;i++){const t=Math.min(duration-1e-6,i/steps*duration);times.push(i/steps*duration);m.setTime(t);source.scene.updateMatrixWorld(true);restore();
for(const n of ordered){if(name==='cast'&&/(UpLeg|Leg|Foot|ToeBase)$/.test(n.name)&&idlePose){n.quaternion.copy(idlePose.get(n.name));n.updateMatrixWorld(true);continue;}
const sn='mixamorig'+mapping[n.name],sq=source.get(sn).getWorldQuaternion(new T.Quaternion()),restQ=quat(source.bind.get(sn)),delta=align.clone().multiply(sq.multiply(restQ.invert())).multiply(inv),desired=delta.multiply(corrected.get(n.name));n.quaternion.copy(n.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(desired)).normalize();n.updateMatrixWorld(true);}
// Keep torso readable and prevent imported shoulder rotations pulling sleeves through the body.
if(name!=='hit'&&name!=='death')for(const n of ordered){if(['mixamorigHips','mixamorigSpine','mixamorigSpine2','mixamorigNeck','mixamorigHead'].includes(n.name)){n.quaternion.copy(rest[target.nodes.indexOf(n)].q.clone().slerp(n.quaternion,name==='cast'?.13:.25));n.updateMatrixWorld(true);}if(['mixamorigLeftShoulder','mixamorigRightShoulder'].includes(n.name)){n.quaternion.copy(rest[target.nodes.indexOf(n)].q);n.updateMatrixWorld(true);}}
function aim(a,b,dir){const n=target.get(a),end=target.get(b),from=end.getWorldPosition(new T.Vector3()).sub(n.getWorldPosition(new T.Vector3())).normalize(),to=new T.Vector3(...dir).normalize(),world=new T.Quaternion().setFromUnitVectors(from,to).multiply(n.getWorldQuaternion(new T.Quaternion()));n.quaternion.copy(n.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world)).normalize();n.updateMatrixWorld(true);}
const phase=t/duration,swing=name==='walk'?.18*Math.sin(2*Math.PI*phase):.02*Math.sin(2*Math.PI*phase),dirs={lu:[.04+swing,-1,-.29],lf:[.13+swing,-1,-.10],ru:[.04-swing,-1,.29],rf:[.13-swing,-1,.10]};
if(name==='cast'){
const keys=[[0,[.04,-1,.29],[.13,-1,.10]],[.25,[.5,-.75,.38],[.7,.55,-.20]],[.44,[1,-.10,.18],[1,.10,-.10]],[.58,[1,-.10,.18],[1,.10,-.10]],[1,[.04,-1,.29],[.13,-1,.10]]];
let k=0;while(k<keys.length-2&&phase>keys[k+1][0])k++;const f=(phase-keys[k][0])/(keys[k+1][0]-keys[k][0]),ease=f*f*(3-2*f);
dirs.ru=keys[k][1].map((v,i)=>v+(keys[k+1][1][i]-v)*ease);dirs.rf=keys[k][2].map((v,i)=>v+(keys[k+1][2][i]-v)*ease);const w=Math.sin(Math.PI*phase);dirs.lf=[.13+.30*w,-1+.30*w,-.10];}
if(name!=='hit'&&name!=='death'){aim('mixamorigLeftArm','mixamorigLeftForeArm',dirs.lu);aim('mixamorigLeftForeArm','mixamorigLeftHand',dirs.lf);aim('mixamorigRightArm','mixamorigRightForeArm',dirs.ru);aim('mixamorigRightForeArm','mixamorigRightHand',dirs.rf);
for(const [hand,fore]of [['mixamorigLeftHand','mixamorigLeftForeArm'],['mixamorigRightHand','mixamorigRightForeArm']]){const n=target.get(hand),parent=target.get(fore),world=parent.getWorldQuaternion(new T.Quaternion()).multiply(quat(target.bind.get(fore)).invert()).multiply(quat(target.bind.get(hand)));n.quaternion.copy(n.parent.getWorldQuaternion(new T.Quaternion()).invert().multiply(world)).normalize();n.updateMatrixWorld(true);}
}
for(const n of ordered){const v=values.get(n.name),q=n.quaternion.clone();if(v.length&&q.dot(new T.Quaternion().fromArray(v,v.length-4))<0)q.set(-q.x,-q.y,-q.z,-q.w);v.push(...q.toArray());}
const root=target.get('Root'),hips=source.get('mixamorigHips');
const deltaPos=hips.getWorldPosition(new T.Vector3()).sub(pos(source,'mixamorigHips')).applyQuaternion(align);
const ratio=pos(target,'mixamorigHips').y/pos(source,'mixamorigHips').y;
deltaPos.multiplyScalar(ratio).applyQuaternion(root.parent.getWorldQuaternion(new T.Quaternion()).invert());
const ps=root.parent.getWorldScale(new T.Vector3());deltaPos.divide(ps);
rootValues.push(...root.position.clone().add(deltaPos).toArray());if(name==='idle'&&i===0)idlePose=new Map(ordered.map(n=>[n.name,n.quaternion.clone()]));
}
m.stopAllAction();const tracks=[...values].map(([n,v])=>new T.QuaternionKeyframeTrack(n+'.quaternion',times,v));
if(name==='idle'||name==='walk'){// Match loop endpoints without a visible end-frame pop.
for(const tr of tracks){const n=tr.values.length;tr.values.set(tr.values.slice(0,4),n-4);}}
tracks.push(new T.VectorKeyframeTrack('Root.position',times,rootValues));const gp=base+'/grounding.json';if(fs.existsSync(gp)){const g=JSON.parse(fs.readFileSync(gp,'utf8'))[name];tracks.push(new T.VectorKeyframeTrack('Root.position',g.times,g.positions));}const clip=new T.AnimationClip(name,duration,tracks);assert(clip.validate());clips.push(clip);report.push({name,source:srcName,duration,frames:times.length,tracks:tracks.length});fs.writeFileSync(base+'/'+name+'.animation.json',JSON.stringify(T.AnimationClip.toJSON(clip)));
}
const j=structuredClone(target.j),parts=[target.buf.subarray(target.bin,target.bin+j.buffers[0].byteLength)];let offset=parts[0].length;
function add(arr,type){const pad=(4-offset%4)%4;if(pad){parts.push(Buffer.alloc(pad));offset+=pad;}const b=Buffer.alloc(arr.length*4);arr.forEach((x,i)=>{assert(Number.isFinite(x));b.writeFloatLE(x,i*4);});const v=j.bufferViews.length;j.bufferViews.push({buffer:0,byteOffset:offset,byteLength:b.length});parts.push(b);offset+=b.length;const a=j.accessors.length;j.accessors.push({bufferView:v,componentType:5126,count:arr.length/(type==='SCALAR'?1:type==='VEC3'?3:4),type,...(type==='SCALAR'?{min:[arr[0]],max:[arr.at(-1)]}:{})});return a;}
j.animations=[...j.animations,...clips.map(c=>{const samplers=[],channels=[];for(const tr of c.tracks){const name=tr.name.replace(/\.(quaternion|position)$/,''),node=target.nodes.findIndex(n=>n.name===name);assert(node>=0);samplers.push({input:add([...tr.times],'SCALAR'),output:add([...tr.values],tr.name.endsWith('.position')?'VEC3':'VEC4'),interpolation:'LINEAR'});channels.push({sampler:samplers.length-1,target:{node,path:tr.name.endsWith('.position')?'translation':'rotation'}});}return{name:c.name,samplers,channels};})];
j.buffers[0].byteLength=offset;let jb=Buffer.from(JSON.stringify(j));jb=Buffer.concat([jb,Buffer.alloc((4-jb.length%4)%4,32)]);let bb=Buffer.concat(parts);bb=Buffer.concat([bb,Buffer.alloc((4-bb.length%4)%4)]);const head=Buffer.alloc(20);head.writeUInt32LE(0x46546c67);head.writeUInt32LE(2,4);head.writeUInt32LE(28+jb.length+bb.length,8);head.writeUInt32LE(jb.length,12);head.writeUInt32LE(0x4e4f534a,16);const bh=Buffer.alloc(8);bh.writeUInt32LE(bb.length);bh.writeUInt32LE(0x004e4942,4);
fs.writeFileSync(base+'/rabbit-healer-combat.glb',Buffer.concat([head,jb,bh,bb]));fs.writeFileSync(base+'/animation-build.json',JSON.stringify({method:'local anatomical world-space retarget; preserved mesh, weights and textures',additionalCredits:0,mapping,clips:report},null,2));console.log(JSON.stringify(report));